# Generated by Django 4.2.27 on 2026-01-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='Semestre')),
                ('requiere_tutoria_individual', models.BooleanField(default=False, verbose_name='Requiere Tutoría Individual')),
                ('motivo_tutoria_individual', models.TextField(blank=True, verbose_name='Motivo Tutoría Individual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('programa_educativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='administracion.programaeducativo', verbose_name='Programa Educativo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
