# Generated by Django 4.2.27 on 2026-01-11 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Asignado'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['matricula'], name='alumnos_alu_matricu_023eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['programa_educativo', 'semestre'], name='alumnos_alu_program_e29037_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['tutor'], name='alumnos_alu_tutor_i_c3f460_idx'),
        ),
    ]
