# Generated by Django 4.2.27 on 2026-01-11 01:32

import apps.reportes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoReporteGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_alumnos_atendidos', models.PositiveIntegerField(default=0, verbose_name='Número de Alumnos Atendidos')),
                ('num_alumnos_grupo', models.PositiveIntegerField(default=0, verbose_name='Número de Alumnos en Grupo')),
                ('temas_tratados', models.TextField(blank=True, verbose_name='Temas Tratados')),
                ('problematicas_detectadas', models.TextField(blank=True, verbose_name='Problemáticas Detectadas')),
                ('alumnos_riesgo_ids', models.JSONField(blank=True, default=list, verbose_name='IDs Alumnos en Riesgo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_sesion', models.DateField(blank=True, null=True, verbose_name='Fecha de Sesión')),
            ],
            options={
                'verbose_name': 'Dato Reporte Grupal',
                'verbose_name_plural': 'Datos Reportes Grupales',
            },
        ),
        migrations.CreateModel(
            name='DatoReporteIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('deficiente', 'Deficiente')], max_length=20, verbose_name='Nivel de Asistencia')),
                ('rendimiento', models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('muy_bajo', 'Muy Bajo')], max_length=20, verbose_name='Nivel de Rendimiento')),
                ('materias_riesgo', models.TextField(blank=True, verbose_name='Materias en Riesgo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('fecha_sesion', models.DateField(blank=True, null=True, verbose_name='Fecha de Sesión')),
            ],
            options={
                'verbose_name': 'Dato Reporte Individual',
                'verbose_name_plural': 'Datos Reportes Individuales',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('ind_inicial', 'Tutoría Individual - Inicial'), ('ind_medio', 'Tutoría Individual - Medio Semestre'), ('ind_final', 'Tutoría Individual - Final'), ('grup_inicial', 'Tutoría Grupal - Inicial'), ('grup_medio', 'Tutoría Grupal - Medio Semestre'), ('grup_final', 'Tutoría Grupal - Final')], max_length=20, verbose_name='Tipo de Reporte')),
                ('archivo_original', models.FileField(upload_to=apps.reportes.models.reporte_upload_path, verbose_name='Archivo Original')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='administracion.periodoacademico', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
