# Generated by Django 4.2.27 on 2026-01-11 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        ('alumnos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='datoreporteindividual',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_reportes', to='alumnos.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='datoreporteindividual',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_individuales', to='reportes.reporte', verbose_name='Reporte'),
        ),
        migrations.AddField(
            model_name='datoreportegrupal',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_grupales', to='reportes.reporte', verbose_name='Reporte'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['tutor', 'tipo_reporte'], name='reportes_re_tutor_i_f50a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['periodo', 'estado'], name='reportes_re_periodo_cff75a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datoreporteindividual',
            unique_together={('reporte', 'alumno')},
        ),
    ]
